<a href="https://colab.research.google.com/github/naidu199/Machine_Learn/blob/main/Multi_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
data=pd.read_csv("https://raw.githubusercontent.com/nandu19k/multiple-linear-regression/master/50_Startups.csv")
data.head(10)
#to check NULL valus in the dataset data.isna().sum()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [8]:
x=data.iloc[:,:-2].values
y=data.iloc[:,-1].values


array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [11]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.2)


array([ 89949.14, 108552.04, 156122.51,  42559.73, 118474.03, 126992.93,
       152211.77, 144259.4 , 141585.52,  96712.8 ])

In [14]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(xtrain,ytrain)

LinearRegression()

In [26]:
yp=reg.predict(xtest)
yp

array([ 89205.58494492, 113322.87999409, 158380.89564843,  46418.42229589,
       115344.27092221, 115826.18080423, 150533.22978411, 135041.09838769,
       128268.57919246,  87746.96838292])

In [17]:
ytest

array([ 89949.14, 108552.04, 156122.51,  42559.73, 118474.03, 126992.93,
       152211.77, 144259.4 , 141585.52,  96712.8 ])

In [18]:
from sklearn.metrics import mean_squared_error
mean_squared_error(ytest,yp)

52331691.07559253

In [19]:
from sklearn.metrics import r2_score
r2_score(ytest,yp)

0.9522979351404004

In [20]:
reg.coef_

array([ 0.81571857, -0.03436096,  0.02003369])

In [24]:
xtest

array([[ 44069.95,  51283.14, 197029.42],
       [ 77044.01,  99281.34, 140574.81],
       [134615.46, 147198.87, 127716.82],
       [     0.  , 135426.92,      0.  ],
       [ 76253.86, 113867.3 , 298664.47],
       [ 78013.11, 121597.55, 264346.06],
       [120542.52, 148718.95, 311613.29],
       [100671.96,  91790.61, 249744.55],
       [ 93863.75, 127320.38, 249839.44],
       [ 46426.07, 157693.92, 210797.67]])